# Linux/Docker Maven build defaults (also copied to build.properties for local overrides)
jdbc.url=jdbc:postgresql://postgresql:5432/hmdm
jdbc.driver=org.postgresql.Driver
jdbc.username=hmdm
jdbc.password=hmdm

base.directory=/opt/hmdm
files.directory=/opt/hmdm/files
base.url=http://localhost:8080

usage.scenario=private
secure.enrollment=0
hash.secret=changeme-C3z9vi54
role.orgadmin.id=2

plugins.files.directory=/opt/hmdm/plugins
initialization.completion.signal.file=/opt/hmdm/initialized.txt

aapt.command=aapt
log4j.config=file:///log4j-hmdm.xml

plugin.devicelog.persistence.config.class=com.hmdm.plugins.devicelog.persistence.postgres.DeviceLogPostgresPersistenceConfiguration

mqtt.server.uri=localhost:31000
mqtt.auth=true
mqtt.message.delay=1000
device.fast.search.chars=5

smtp.host=smtp.mailgun.org
smtp.port=25
smtp.ssl=0
smtp.starttls=0
smtp.username=myacct@example.com
smtp.password=changeme
smtp.from=noreply@example.com

jwt.secretkey=20c68f0d9185b1d18cf6add1e8b491fd89529a44
jwt.validity=86400
jwt.validityrememberme=2592000
