package metadata

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDetectInstallerArgs(t *testing.T) {
	t.Run("msi extension", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "app.msi")
		if err := os.WriteFile(path, []byte("dummy"), 0o644); err != nil {
			t.Fatal(err)
		}

		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != "/quiet /norestart" {
			t.Fatalf("DetectInstallerArgs() = %q, want %q", got, "/quiet /norestart")
		}
	})

	t.Run("nsis exehead signature", func(t *testing.T) {
		path := writeDetectFixture(t, "nsis.exe", append([]byte("prefix-"), nsisExeheadSignature...))
		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != "/S" {
			t.Fatalf("DetectInstallerArgs() = %q, want %q", got, "/S")
		}
	})

	t.Run("nsis nullsoft string", func(t *testing.T) {
		path := writeDetectFixture(t, "nsis2.exe", []byte("built with Nullsoft installer"))
		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != "/S" {
			t.Fatalf("DetectInstallerArgs() = %q, want %q", got, "/S")
		}
	})

	t.Run("inno setup signature", func(t *testing.T) {
		path := writeDetectFixture(t, "inno.exe", append([]byte("meta "), innoSetupSignature...))
		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" {
			t.Fatalf("DetectInstallerArgs() = %q, want %q", got, "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART")
		}
	})

	t.Run("installshield signature", func(t *testing.T) {
		path := writeDetectFixture(t, "is.exe", append(installShieldSignature, []byte(" setup")...))
		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != `/s /v"/qn"` {
			t.Fatalf("DetectInstallerArgs() = %q, want %q", got, `/s /v"/qn"`)
		}
	})

	t.Run("wix burn signature", func(t *testing.T) {
		path := writeDetectFixture(t, "wix.exe", []byte("generated by WiX Toolset burn engine"))
		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != "-quiet -norestart" {
			t.Fatalf("DetectInstallerArgs() = %q, want %q", got, "-quiet -norestart")
		}
	})

	t.Run("suffix scan finds marker", func(t *testing.T) {
		padding := make([]byte, maxInstallerScanBytes+1024)
		for i := range padding {
			padding[i] = 'x'
		}
		content := append(padding, innoSetupSignature...)
		path := writeDetectFixture(t, "large-inno.exe", content)

		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" {
			t.Fatalf("DetectInstallerArgs() = %q, want inno args", got)
		}
	})

	t.Run("unknown exe", func(t *testing.T) {
		path := writeDetectFixture(t, "generic.exe", []byte("no installer markers here"))
		got, err := DetectInstallerArgs(path)
		if err != nil {
			t.Fatalf("DetectInstallerArgs() error = %v", err)
		}
		if got != "" {
			t.Fatalf("DetectInstallerArgs() = %q, want empty", got)
		}
	})
}

func writeDetectFixture(t *testing.T, name string, content []byte) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}
